on: workflow_dispatch

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Install .NET 9
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: 'Build'
      run: ./publish.cmd Release